# Configuration for branch protection
# This file is read by the GitHub branch protection settings

# Branch protection rules for 'main' branch
main:
  # Require pull request reviews before merging
  required_pull_request_reviews:
    required_approving_review_count: 1
    require_code_owner_reviews: true
    dismiss_stale_reviews: true
    require_last_push_approval: true
    
  # Require status checks to pass before merging
  required_status_checks:
    strict: true
    contexts:
      - test
      
  # Restrict who can push to matching branches
  enforce_admins: false
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false
  
  # Required conversation resolution before merging
  required_conversation_resolution: true
  
  # Lock branch
  lock_branch: false
  
  # Allow fork syncing
  allow_fork_syncing: true
